// packages/mcp-server/src/generators/templates/stencil.template.ts
import { GeneratorContext, GeneratedComponent } from "../types";
import {
  toPascalCase,
  toKebabCase,
  getAllInputs,
  getAllEvents,
  getTypeScriptType,
  getDefaultValue,
} from "../utils";

export function generateStencilComponent(context: GeneratorContext): string {
  const { surface, componentName, riveSrc } = context;
  const inputs = getAllInputs(surface);
  const events = getAllEvents(surface);
  const stateMachineName = surface.stateMachines[0]?.name || "DefaultSM";
  const kebabName = toKebabCase(componentName);

  // Generate property declarations
  const propertyDeclarations = inputs.map(input => `
  /**
   * State machine input: ${input.name}
   */
  @Prop() ${input.name}!: ${getTypeScriptType(input.type)};`
  ).join("\n");

  // Generate event declarations
  const eventDeclarations = events.map(event => `
  /**
   * Emitted when: ${event.name}${event.description ? ` - ${event.description}` : ""}
   */
  @Event() ${toKebabCase(event.name)}: EventEmitter<any>;`
  ).join("\n");

  // Generate watch handlers
  const watchHandlers = inputs.map(input => `
  @Watch("${input.name}")
  handle${toPascalCase(input.name)}Change(newValue: ${getTypeScriptType(input.type)}) {
    if (this.rive && this.stateMachineInputs.${input.name}) {
      this.stateMachineInputs.${input.name}.value = newValue;
    }
  }`
  ).join("\n");

  // Generate event handler setup
  const eventHandlerSetup = events.length > 0 ? `
    // Set up event listeners
    this.rive.on("event", (event: any) => {
${events.map(event => `      if (event.data?.name === "${event.name}") {
        this.${toKebabCase(event.name)}.emit(event.data);
      }`).join("\n")}
    });` : "";

  return `import { Component, Prop, Element, Watch, Event, EventEmitter, h } from "@stencil/core";
import { Rive } from "@rive-app/canvas";

/**
 * ${componentName} - A Rive-powered web component
 *
 * This component is automatically generated and provides type-safe props
 * for all state machine inputs and events.
 *
 * @slot default - Default slot content
 */
@Component({
  tag: "${kebabName}",
  styleUrl: "${kebabName}.css",
  shadow: true,
})
export class ${componentName} {
  @Element() el!: HTMLElement;

  private canvasElement?: HTMLCanvasElement;
  private rive?: Rive;
  private stateMachineInputs: any = {};
${propertyDeclarations}
${eventDeclarations}

  componentDidLoad() {
    this.initializeRive();
  }

  disconnectedCallback() {
    this.cleanup();
  }
${watchHandlers}

  private initializeRive() {
    if (!this.canvasElement) return;

    this.rive = new Rive({
      src: "${riveSrc}",
      canvas: this.canvasElement,
      stateMachines: "${stateMachineName}",
      autoplay: true,
      onLoad: () => {
        this.setupStateMachine();
      },
    });
  }

  private setupStateMachine() {
    if (!this.rive) return;

    // Get state machine inputs
    const inputs = this.rive.stateMachineInputs("${stateMachineName}");
    if (!inputs) return;

    this.stateMachineInputs = {
${inputs.map(input => `      ${input.name}: inputs.find((input: any) => input.name === "${input.name}")`).join(",\n")}
    };

    // Set initial values
${inputs.map(input => `    if (this.${input.name} !== undefined && this.stateMachineInputs.${input.name}) {
      this.stateMachineInputs.${input.name}.value = this.${input.name};
    }`).join("\n")}
${eventHandlerSetup}
  }

  private cleanup() {
    if (this.rive) {
      this.rive.cleanup();
      this.rive = undefined;
    }
  }

  render() {
    return (
      <div class="${kebabName}-wrapper">
        <canvas
          ref={(el) => (this.canvasElement = el as HTMLCanvasElement)}
        ></canvas>
      </div>
    );
  }
}
`;
}

export function generateStencilCSS(componentName: string): string {
  const kebabName = toKebabCase(componentName);

  return `:host {
  display: block;
  width: 100%;
  height: 100%;
}

.${kebabName}-wrapper {
  width: 100%;
  height: 100%;
  position: relative;
}

canvas {
  width: 100%;
  height: 100%;
  display: block;
}
`;
}

export async function generateStencil(context: GeneratorContext): Promise<GeneratedComponent> {
  const code = generateStencilComponent(context);
  const cssCode = generateStencilCSS(context.componentName);
  const kebabName = toKebabCase(context.componentName);

  const filePath = context.outputPath ||
    `/Users/gregorystarr/projects/rive-projects/rive-mcp-server-core/libs/rive-components/src/${kebabName}.tsx`;

  const cssFilePath = `/Users/gregorystarr/projects/rive-projects/rive-mcp-server-core/libs/rive-components/src/${kebabName}.css`;

  return {
    code: code + "\n\n// CSS File:\n// " + cssFilePath + "\n" + cssCode,
    filePath,
    framework: "stencil",
    componentName: context.componentName,
  };
}

// packages/mcp-server/src/generators/templates/react.template.ts
import { GeneratorContext, GeneratedComponent } from "../types";
import {
  toPascalCase,
  getAllInputs,
  getAllEvents,
  getTypeScriptType,
  getDefaultValue,
} from "../utils";

export function generateReactComponent(context: GeneratorContext): string {
  const { surface, componentName, riveSrc } = context;
  const inputs = getAllInputs(surface);
  const events = getAllEvents(surface);
  const stateMachineName = surface.stateMachines[0]?.name || "DefaultSM";

  // Generate props interface
  const propsInterface = generatePropsInterface(componentName, inputs, events);

  // Generate input hooks and effects
  const inputHooks = inputs.map(input =>
    `  const ${input.name}Input = useStateMachineInput(rive, "${stateMachineName}", "${input.name}");`
  ).join("\n");

  const inputEffects = inputs.map(input => `
  useEffect(() => {
    if (${input.name}Input) ${input.name}Input.value = ${input.name};
  }, [${input.name}, ${input.name}Input]);`
  ).join("\n");

  // Generate event handlers
  const eventHandlers = events.map(event => `
  useEffect(() => {
    if (!rive || !on${toPascalCase(event.name)}) return;
    const handler = (riveEvent: any) => {
      if (riveEvent.data?.name === "${event.name}") {
        on${toPascalCase(event.name)}(riveEvent.data);
      }
    };
    rive.on("event", handler);
    return () => {
      rive.off("event", handler);
    };
  }, [rive, on${toPascalCase(event.name)}]);`
  ).join("\n");

  // Generate component code
  return `import React, { useEffect } from "react";
import { useRive, useStateMachineInput } from "@rive-app/react-canvas";

${propsInterface}

/**
 * ${componentName} - A Rive-powered component
 *
 * This component is automatically generated and provides type-safe props
 * for all state machine inputs and events.
 *
 * @component
 */
export const ${componentName}: React.FC<${componentName}Props> = ({
${inputs.map(input => `  ${input.name}`).join(",\n")}${events.length > 0 ? "," : ""}
${events.map(event => `  on${toPascalCase(event.name)}`).join(",\n")}
}) => {
  const { rive, RiveComponent } = useRive({
    src: "${riveSrc}",
    stateMachines: ["${stateMachineName}"],
    autoplay: true
  });

${inputHooks}
${inputEffects}
${eventHandlers}

  return (
    <div className="${componentName.toLowerCase()}-wrapper">
      <RiveComponent />
    </div>
  );
};
`;
}

function generatePropsInterface(
  componentName: string,
  inputs: Array<{ name: string; type: "bool" | "number" | "string"; defaultValue?: any }>,
  events: Array<{ name: string; description?: string }>
): string {
  const lines: string[] = [];

  lines.push(`type ${componentName}Props = {`);

  // Add input props with JSDoc
  inputs.forEach(input => {
    lines.push(`  /**`);
    lines.push(`   * State machine input: ${input.name}`);
    if (input.defaultValue !== undefined) {
      lines.push(`   * @default ${input.defaultValue}`);
    }
    lines.push(`   */`);
    lines.push(`  ${input.name}: ${getTypeScriptType(input.type)};`);
  });

  // Add event handler props with JSDoc
  events.forEach(event => {
    lines.push(`  /**`);
    lines.push(`   * Event handler for: ${event.name}`);
    if (event.description) {
      lines.push(`   * ${event.description}`);
    }
    lines.push(`   */`);
    lines.push(`  on${toPascalCase(event.name)}?: (payload: any) => void;`);
  });

  lines.push(`};`);

  return lines.join("\n");
}

export async function generateReact(context: GeneratorContext): Promise<GeneratedComponent> {
  const code = generateReactComponent(context);
  const filePath = context.outputPath ||
    `/Users/gregorystarr/projects/rive-projects/rive-mcp-server-core/libs/rive-components/src/${context.componentName}.tsx`;

  return {
    code,
    filePath,
    framework: "react",
    componentName: context.componentName,
  };
}
